// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using skillet.Data;

namespace skillet.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("skillet.Models.Household", b =>
                {
                    b.Property<int>("HouseholdId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("HeadUserId");

                    b.Property<string>("HouseCity");

                    b.Property<string>("HouseName");

                    b.Property<string>("HouseState");

                    b.Property<string>("HouseStreet");

                    b.Property<int>("HouseZip");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("HouseholdId");

                    b.HasIndex("HeadUserId");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("skillet.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<int>("HouseholdId");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("skillet.Models.Household", b =>
                {
                    b.HasOne("skillet.Models.User", "Head")
                        .WithMany()
                        .HasForeignKey("HeadUserId");
                });

            modelBuilder.Entity("skillet.Models.User", b =>
                {
                    b.HasOne("skillet.Models.Household")
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
